[colors.bright]
black = "0x928374"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe3a84e"

[colors.normal]
black = "0x665c54"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe78a4e"

[colors.primary]
background = "0x282828"
foreground = "0xdfbf8e"

[cursor]
blink_interval = 400
thickness = 0.1
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 7

[font.bold]
family = "Gohu GohuFont"
style = "Regular"

[font.normal]
family = "Gohu GohuFont"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
multiplier = 3

[shell]
program = "/bin/fish"

[window]
decorations = "none"
opacity = 1

[window.padding]
x = 10
y = 10
