[cursor]
blink_interval = 400
thickness = 0.1
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 9

[font.bold]
family = "Misc Tamsyn"
style = "Regular"

[font.normal]
family = "Misc Tamsyn"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
multiplier = 3

[shell]
program = "/bin/fish"

[window]
decorations = "none"
opacity = 1

[window.padding]
x = 10
y = 10

[colors.primary]
background = "0x1d2021"
foreground = "0xd4be98"

[colors.normal]
black   = "0x32302f"
red     = "0xea6962"
green   = "0xa9b665"
yellow  = "0xd8a657"
blue    = "0x7daea3"
magenta = "0xd3869b"
cyan    = "0x89b482"
white   = "0xd4be98"
